### PR TITLE
ID-69

### PR DESCRIPTION
**Pull request by NiHS-Bon**
@lucas added Verification Workflow Diagram.
Also added some words to the introduction.

When reviewed this complete ID-69...

https://dltx.atlassian.net/browse/ID-69?atlOrigin=eyJpIjoiNzQyYTM0NWE5NGQwNDI4YTgyZGUwNjQ1YTkwZjExZGQiLCJwIjoiaiJ9

### CODE REVIEW

**Review by TomDodson — CHANGES_REQUESTED** [review]
@NiHS-Bon Can you replace Verification Workflow Diagram highres version? Everything else looks good

**Review by NiHS-Bon — COMMENTED** [review]
Picture updated

**Review by TomDodson — APPROVED** [review]
Image fixed

**Review by TomDodson — APPROVED** [review]
Image fixed

**Review by TomDodson — APPROVED** [review]
Changes accepted

**Review by TomDodson — APPROVED** [review]
Imaged accepted

**Pull request merged**
